# Generated by Django 4.2.19 on 2025-02-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_docker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='account_number',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
